# Generated by Django 5.1.6 on 2025-03-05 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 13, 50, 41, 651429)),
        ),
    ]
