# Generated by Django 5.1.6 on 2025-03-05 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='images/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 14, 16, 28, 926484)),
        ),
    ]
